on: [push]

jobs:
  validate_changelog:
    runs-on: ubuntu-latest
    name: Validate Changelog
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use changelog-validate action
        uses: ./ # Uses an action in the root directory
        with:
          token: ${{ github.token }}
          changelogs: '[{"watchFolder": "examples", "file": "examples/CHANGELOG.md"}]'


